version: '3'
services:
  node:
    build:
      context: .
    environment: 
      - BOT_ID=$BOT_ID
      - BOT_TOKEN=$BOT_TOKEN
      - VOCAL_PITCH=200
      - VOCAL_VOICE=mazzo.htsvoice
    tty: true
    volumes:
      - .:/app
      -  /app/node_modules